#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if git rev-parse --verify HEAD >/dev/null 2>&1
then
  against=HEAD
else
  # Initial commit: diff against an empty tree object
  against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi
PWD=`pwd`
cmd_dir=null
modulr_dir=null
# app module
if [ -e $PWD/gradlew ]; then
  cmd_dir=$PWD
  modulr_dir=$cmd_dir/app
# sub repository module
else
  cmd_dir=`cd "$PWD"/../../; pwd`
  modulr_dir=$PWD
fi
$cmd_dir/gradlew -PcheckCommit="true" -p $modulr_dir checkCodeStyle
if [ $? -eq 0   ]; then
    echo "checkCodeStyle OK"
else
    exit [[ $ERROR_INFO =~ "checkCodeStyle" ]] && exit 1  
fi

